build:
  cuda_version: "12.3"
  system_packages:
    - "libssl-dev"
  python_packages:
    - "git+https://github.com/huggingface/transformers.git@main"
    - "git+https://github.com/chu-tianxiang/vllm-gptq.git@gptq_hf"
    - "accelerate"
