build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torch==2.0.1"
    - "git+https://github.com/chu-tianxiang/vllm-gptq.git@gptq_hf"
    - "transformers"
    - "accelerate"
    - "safetensors"
    
