build:
  cuda_version: "12.3"
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torch==2.0.1"
    - "vllm==0.2.1.post1"
    - "git+https://github.com/huggingface/transformers.git@main"    
    - "accelerate"
